### ISSUE TITLE
Generated KML files does not output altitudes <0

### ISSUE THREAD

**Issue by elcf** [Aceinna/gnss-ins-sim#22]
I'm not sure if this was done on purpose, but if an altitude is <0 (either reference or algo), the KML altitude is set at 0. The output pos CSV files however state the negative altitudes.

Edit: Actually, it seems that the altitude data is always 0 in display of Google Earth Pro, but when altitude is <0, it shows up as 0 in the KML file.

**Comment by elcf** [comment]
For the issue that the KML has positive altitude data, but in Google Earth Pro it shows as 0, the reason is that the default "altitudeMode" is set to "clampToGround" Source: https://developers.google.com/kml/documentation/kmlreference#gx:altitudemode
So it seems it has to be made explicit that the "altitudeMode" is "absolute".

**Comment by elcf** [comment]
Saw that in line 122-123 of kml_gen.py, `if lla[i][2] < 0: lla[i][2] = 0`. Is there a reason this was done? I will change it on my code since I'm using it for underwater sim.

**Comment by dxg-aceinna** [comment]
Hi elcf,

Thank you for your feedback. This was done on purpose. When there is negative altitude and the altitude mode is "absolute", this point is not showed on Google Earth because it might be underground. So I forced the altitude to be non-negative.
![图片](https://user-images.githubusercontent.com/35481017/106073415-fd48a900-6144-11eb-9b3f-88d376166f1a.png)
![图片](https://user-images.githubusercontent.com/35481017/106073418-00439980-6145-11eb-9270-f8e9c3efa200.png)

**Comment by elcf** [comment]
Hi dxg, understood, thank you.
