### ISSUE TITLE
Accelerometer coordinate frame

### ISSUE THREAD

**Issue by oniht** [Aceinna/gnss-ins-sim#46]
Hi, I have an issue with getting the simulated accelerometer and gyroscope measurements to match with a real life case. I'm trying to replicate IMU data that was recorded during a metro ride that includes 2 approx. 75 deg turns. First left then right. I flipped the IMU with initial pitch of 180 deg to get positive z-acceleration and assigned an initial velocity v_y = 20m/s. Then I simulated these 2 turns with constant yaw rate during 40 sec. (I ignored the acceleration periods in y-direction)

The results match pretty well with the real life case except that the acceleration in x-direction is negative during the left turn and positive during the right turn. I would assume that these should be opposite if the accelerometer coordinate frame follows the right hand convention?

![tapiola-acc](https://github.com/Aceinna/gnss-ins-sim/assets/49974894/1041fc34-33e3-419e-b559-c7137e5257c1)
![tapiola-gyro](https://github.com/Aceinna/gnss-ins-sim/assets/49974894/8724fa67-dbe6-4eb6-87ed-297359a5d32a)
![tapiola-sim-acc](https://github.com/Aceinna/gnss-ins-sim/assets/49974894/32606c4a-9292-42b4-86bf-46839ba2596c)
![tapiola-sim-gyro](https://github.com/Aceinna/gnss-ins-sim/assets/49974894/b0f1f535-c858-4e0c-8802-141370c1e5ac)

**Comment by dxg-aceinna** [comment]
Could you provide a picture about how the IMU (in the simulaiton) is installed on the metro when you apply the pitch = 180deg flilp?
To me, usually ZYX sequence is used in the simulation by default. The range for the pitch angle should be [-90, 90]deg. Besides, even if pitch = 180, the X acceleration should still point along the motion direction of the metro. Without velocity amplitude change, X acceleration should be always zero while the Y acceleration should show acceleration due to rotation.
